---
# Homepage Settings
title: jaxmind.xyz
description: Pablo's Lab
favicon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/favicon.ico

# Color theme
color: slate
theme: dark

# Header stats
headerStyle: boxed

# Show system stats at the top
useEqualHeights: true

# Quick launch search
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  searchUrl: https://google.com/search?q=
  provider: google

layout:
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Projects:
    style: row
    columns: 3
