#!/usr/bin/env bash
# ============================================================================
#  Hermes Agent — WSL2 Command Routing Setup
#
#  On WSL2, if you have Hermes installed natively on Windows AND in a Linux
#  venv, this script sets up two commands:
#
#    hermes      → runs the Windows-native install (faster, native clipboard,
#                  native terminal, no WSL translation overhead)
#    hermes-wsl  → runs the Linux/WSL2 venv install
#
#  Usage:
#    bash scripts/setup-wsl-routing.sh
#
#  Optional:
#    --bin-dir DIR    Where to install wrappers (default: ~/.local/bin)
#    --win-hermes PATH  Path to Windows hermes.exe (auto-detected)
#    --wsl-hermes PATH  Path to WSL venv hermes (auto-detected)
#    --undo           Remove wrappers and restore original hermes
# ============================================================================

set -euo pipefail

# Defaults
BIN_DIR="${HOME}/.local/bin"
WIN_HERMES=""
WSL_HERMES=""
UNDO=false

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --bin-dir)    BIN_DIR="$2"; shift 2 ;;
        --win-hermes) WIN_HERMES="$2"; shift 2 ;;
        --wsl-hermes) WSL_HERMES="$2"; shift 2 ;;
        --undo)       UNDO=true; shift ;;
        -h|--help)
            sed -n '2,/^# ===/p' "$0" | head -n -1 | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Colors
red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
dim()    { printf '\033[0;90m%s\033[0m\n' "$*"; }

# Check we're on WSL
if ! grep -qi microsoft /proc/version 2>/dev/null; then
    red "This script is only for WSL2. Detected non-WSL Linux."
    exit 1
fi

echo ""
echo "  ☤ Hermes WSL2 Command Routing Setup"
echo "  ======================================"
echo ""

# --- Undo mode ---
if $UNDO; then
    yellow "Removing WSL routing wrappers..."
    rm -f "${BIN_DIR}/hermes" "${BIN_DIR}/hermes-wsl"
    # If there's a venv hermes, restore the symlink
    for venv_hermes in "${HOME}/hermes-venv/bin/hermes" "${HOME}/.venv/bin/hermes"; do
        if [[ -x "$venv_hermes" ]]; then
            ln -sf "$venv_hermes" "${BIN_DIR}/hermes"
            green "Restored: hermes → $venv_hermes"
            break
        fi
    done
    green "Done. WSL routing removed."
    exit 0
fi

# --- Detect Windows hermes.exe ---
if [[ -z "$WIN_HERMES" ]]; then
    # Common install locations
    candidates=(
        "/mnt/c/Users/*/AppData/Local/Programs/Python/Python3*/Scripts/hermes.exe"
        "/mnt/c/Users/*/AppData/Local/Programs/hermes/hermes.exe"
        "/mnt/c/Users/*/AppData/Local/hermes-agent/.venv/Scripts/hermes.exe"
    )
    for pattern in "${candidates[@]}"; do
        # shellcheck disable=SC2086
        for match in $pattern; do
            if [[ -x "$match" ]]; then
                WIN_HERMES="$match"
                break 2
            fi
        done
    done
fi

if [[ -z "$WIN_HERMES" ]]; then
    red "Could not find Windows hermes.exe."
    echo "  Install Hermes on Windows first, or pass --win-hermes /path/to/hermes.exe"
    exit 1
fi

dim "  Windows hermes: $WIN_HERMES"

# --- Detect WSL venv hermes ---
if [[ -z "$WSL_HERMES" ]]; then
    candidates=(
        "${HOME}/hermes-venv/bin/hermes"
        "${HOME}/.venv/bin/hermes"
        "${HOME}/.local/share/hermes-agent/.venv/bin/hermes"
    )
    for c in "${candidates[@]}"; do
        if [[ -x "$c" ]]; then
            WSL_HERMES="$c"
            break
        fi
    done
    # Also check if current hermes in PATH is a venv python script
    if [[ -z "$WSL_HERMES" ]]; then
        current=$(command -v hermes 2>/dev/null || true)
        if [[ -n "$current" ]] && head -1 "$current" 2>/dev/null | grep -q python; then
            WSL_HERMES="$current"
        fi
    fi
fi

if [[ -z "$WSL_HERMES" ]]; then
    yellow "  No WSL hermes venv found — only setting up Windows routing."
    yellow "  hermes-wsl will not be created."
    WSL_ONLY=false
else
    WSL_ONLY=true
    dim "  WSL hermes:     $WSL_HERMES"
fi

echo ""

# --- Create bin dir ---
mkdir -p "$BIN_DIR"

# --- Write hermes wrapper (routes to Windows) ---
cat > "${BIN_DIR}/hermes" << WRAPPER
#!/bin/bash
# Hermes WSL2 routing — runs Windows-native Hermes
# Generated by setup-wsl-routing.sh
exec ${WIN_HERMES} "\$@"
WRAPPER
chmod +x "${BIN_DIR}/hermes"
green "  ✔ ${BIN_DIR}/hermes → Windows native (${WIN_HERMES})"

# --- Write hermes-wsl wrapper (routes to Linux venv) ---
if [[ "$WSL_ONLY" == "true" ]]; then
    # If it's a symlink already, remove it first
    rm -f "${BIN_DIR}/hermes-wsl"
    cat > "${BIN_DIR}/hermes-wsl" << WRAPPER
#!/bin/bash
# Hermes WSL2 routing — runs Linux/WSL2 venv Hermes
# Generated by setup-wsl-routing.sh
exec ${WSL_HERMES} "\$@"
WRAPPER
    chmod +x "${BIN_DIR}/hermes-wsl"
    green "  ✔ ${BIN_DIR}/hermes-wsl → WSL2 venv (${WSL_HERMES})"
fi

# --- Check PATH ---
echo ""
if echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    green "  ✔ $BIN_DIR is in PATH"
else
    yellow "  ⚠ $BIN_DIR is not in your PATH"
    echo "  Add this to your ~/.bashrc or ~/.profile:"
    echo ""
    echo "    export PATH=\"${BIN_DIR}:\$PATH\""
    echo ""
fi

# --- Summary ---
echo ""
echo "  Commands:"
echo "    hermes       Windows-native Hermes (recommended)"
echo "    hermes-wsl   Linux/WSL2 venv Hermes"
echo ""
green "  Done. Open a new shell or run: source ~/.bashrc"
