#!/usr/bin/env python3
"""Train the routing classifier from collected routing decisions or synthetic data.

Reads labeled routing decisions from state.db (quality_score must be
backfilled first) or from synthetic data generated by generate_synthetic_routing_data.py.
Trains a LogisticRegression model and saves to ~/.hermes/models/routing_classifier.pkl.

Usage:
    python scripts/train_routing_classifier.py [--min-samples 200] [--threshold 0.7]
    python scripts/train_routing_classifier.py --from-synthetic
    python scripts/train_routing_classifier.py --from-synthetic --synthetic-path PATH

Requirements:
    pip install scikit-learn
"""

import argparse
import json
import logging
import pickle
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# Add hermes-agent root to path for imports
HERMES_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(HERMES_ROOT))


def _load_from_db(min_samples: int, threshold: float):
    """Load training data from state.db routing decisions."""
    from hermes_state import SessionDB
    from agent.routing_features import extract_features, features_to_array

    db = SessionDB()
    rows = db.get_routing_decisions(limit=10000, scored_only=True)
    db.close()

    if len(rows) < min_samples:
        logger.error(
            "Only %d scored routing decisions found (need %d). "
            "Run backfill_routing_quality.py first, or use --from-synthetic.",
            len(rows), min_samples
        )
        sys.exit(1)

    logger.info("Loaded %d scored routing decisions from DB", len(rows))

    X = []
    y = []

    for row in rows:
        text = (row.get("message_text") or "").strip()
        depth = int(row.get("conversation_depth") or 0)

        features = extract_features(text, depth)
        X.append(features_to_array(features))

        quality = row.get("quality_score", 0) or 0
        is_cheap_safe = quality >= threshold
        y.append(1 if is_cheap_safe else 0)

    return X, y


def _load_from_synthetic(synthetic_path: Path):
    """Load training data from synthetic JSON file."""
    from agent.routing_features import extract_features, features_to_array

    if not synthetic_path.exists():
        logger.error(
            "Synthetic data file not found: %s\n"
            "Generate it first with: python scripts/generate_synthetic_routing_data.py",
            synthetic_path
        )
        sys.exit(1)

    with open(synthetic_path, "r", encoding="utf-8") as f:
        dataset = json.load(f)

    logger.info("Loaded %d examples from synthetic data", len(dataset))

    X = []
    y = []

    for item in dataset:
        text = item["message"]
        depth = item.get("conversation_depth", 0)

        features = extract_features(text, depth)
        X.append(features_to_array(features))
        y.append(item["label"])

    return X, y


def main():
    parser = argparse.ArgumentParser(description="Train routing classifier")
    parser.add_argument("--min-samples", type=int, default=200,
                        help="Minimum scored samples required to train from DB (default: 200)")
    parser.add_argument("--threshold", type=float, default=0.7,
                        help="Quality score threshold for 'good enough for cheap' (default: 0.7)")
    parser.add_argument("--output", type=str, default=None,
                        help="Output path for .pkl model (default: ~/.hermes/models/routing_classifier.pkl)")
    parser.add_argument("--test-size", type=float, default=0.2,
                        help="Fraction of data for testing (default: 0.2)")
    parser.add_argument("--from-synthetic", action="store_true",
                        help="Train from synthetic data instead of state.db")
    parser.add_argument("--synthetic-path", type=str, default=None,
                        help="Path to synthetic data JSON (default: ~/.hermes/models/synthetic_routing_data.json)")
    args = parser.parse_args()

    try:
        from sklearn.linear_model import LogisticRegression
        from sklearn.model_selection import train_test_split
        from sklearn.metrics import classification_report, confusion_matrix
        from sklearn.calibration import CalibratedClassifierCV
        import numpy as np
    except ImportError:
        logger.error("scikit-learn is required: pip install scikit-learn")
        sys.exit(1)

    from hermes_constants import get_hermes_home
    from agent.routing_features import feature_names

    # Load data from the appropriate source
    if args.from_synthetic:
        default_synthetic = get_hermes_home() / "models" / "synthetic_routing_data.json"
        synthetic_path = Path(args.synthetic_path) if args.synthetic_path else default_synthetic
        X, y = _load_from_synthetic(synthetic_path)
    else:
        X, y = _load_from_db(args.min_samples, args.threshold)

    names = feature_names()
    X = np.array(X)
    y = np.array(y)

    # Report class balance
    n_cheap = int(y.sum())
    n_primary = len(y) - n_cheap
    logger.info("Class balance: cheap-safe=%d, needs-primary=%d", n_cheap, n_primary)

    # Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=42, stratify=y
    )

    # Train
    model = LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42,
    )
    model.fit(X_train, y_train)

    # Evaluate
    y_pred = model.predict(X_test)
    logger.info("\nClassification Report:")
    logger.info(classification_report(y_test, y_pred, target_names=["primary", "cheap"]))
    logger.info("Confusion Matrix:")
    logger.info(confusion_matrix(y_test, y_pred))

    # Feature importances
    logger.info("\nFeature Importances:")
    for name, coef in sorted(zip(names, model.coef_[0]), key=lambda x: abs(x[1]), reverse=True):
        logger.info("  %-25s %+.4f", name, coef)

    # Calibrate confidence threshold: find the threshold that gives >95% precision
    # on the "cheap" class (we want very few false positives — routing to cheap
    # when primary was needed is worse than the reverse)
    test_proba = model.predict_proba(X_test)[:, 1]  # probability of "cheap"
    best_threshold = 0.85  # fallback
    for candidate in [0.70, 0.75, 0.80, 0.85, 0.90, 0.95]:
        predicted_cheap = test_proba >= candidate
        true_positives = ((predicted_cheap) & (y_test == 1)).sum()
        false_positives = ((predicted_cheap) & (y_test == 0)).sum()
        precision = true_positives / max(true_positives + false_positives, 1)
        coverage = predicted_cheap.sum() / len(y_test)
        logger.info("  threshold=%.2f  precision=%.3f  coverage=%.3f", candidate, precision, coverage)
        if precision >= 0.95 and coverage > 0.05:
            best_threshold = candidate
            break

    logger.info("Selected confidence threshold: %.2f", best_threshold)

    # Save
    output_path = Path(args.output) if args.output else get_hermes_home() / "models" / "routing_classifier.pkl"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "wb") as f:
        pickle.dump(model, f)
    logger.info("\nModel saved to %s", output_path)

    # Save metadata (including calibrated threshold)
    meta_path = output_path.with_suffix(".json")
    meta = {
        "training_samples": len(X_train),
        "test_samples": len(X_test),
        "quality_threshold": args.threshold,
        "confidence_threshold": best_threshold,
        "feature_names": names,
        "accuracy": float((y_pred == y_test).mean()),
        "class_balance": {"cheap_safe": n_cheap, "needs_primary": n_primary},
        "data_source": "synthetic" if args.from_synthetic else "state_db",
    }
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    logger.info("Metadata saved to %s", meta_path)


if __name__ == "__main__":
    main()
