#!/usr/bin/env python3
"""Rebuild ~/wiki/skills-index-moc.md by scanning both agents' skill trees.

Walks every SKILL.md under ~/.hermes/skills/ and ~/.openclaw/custom-skills/,
extracts the frontmatter description, and writes a single Obsidian MOC that
groups Hermes skills by category, lists OpenClaw skills, and flags any names
that exist in both trees (likely duplicates that need reconciliation).
"""

import re
import time
from pathlib import Path

HERMES = Path.home() / ".hermes/skills"
OPENCLAW = Path.home() / ".openclaw/custom-skills"
OUTPUT = Path.home() / "wiki/skills-index-moc.md"


def extract_desc(md_path: Path) -> str:
    try:
        text = md_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""
    m = re.search(
        r"^description:\s*(.+?)(?:\n[a-z_-]+:|\n---)",
        text, re.MULTILINE | re.DOTALL,
    )
    if m:
        return re.sub(r"\s+", " ", m.group(1).strip())[:160]
    body = text.split("---", 2)[-1].strip() if text.startswith("---") else text
    for line in body.splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith(">"):
            return s[:160]
    return ""


def walk(root: Path):
    out = []
    if not root.exists():
        return out
    for md in sorted(root.rglob("SKILL.md")):
        rel = md.parent.relative_to(root)
        out.append((str(rel), md.parent.name, extract_desc(md)))
    return out


def main() -> int:
    hermes = walk(HERMES)
    oc = walk(OPENCLAW)

    by_cat: dict = {}
    for rel, name, desc in hermes:
        cat = rel.split("/")[0] if "/" in rel else rel
        by_cat.setdefault(cat, []).append((name, desc))

    hermes_names = {name for _, name, _ in hermes}
    oc_names = {name for _, name, _ in oc}
    dupes = sorted(hermes_names & oc_names)

    today = time.strftime("%Y-%m-%d", time.localtime())
    lines = [
        "---",
        "title: Skills Index (Hermes + OpenClaw)",
        f"updated: {today}",
        "type: summary",
        "tags: [skills, moc, agent-inventory]",
        "---",
        "",
        "# Skills Index MOC",
        "",
        "Single-source catalog of every skill available to [[hermes-role]] and [[openclaw-role]].",
        "Auto-generated by `agent_bus/scripts/build_skills_moc.py`.",
        "",
        f"**Totals:** Hermes {len(hermes)} skills across {len(by_cat)} categories · OpenClaw {len(oc)} custom skills",
        "",
        "## Cross-agent duplicates",
        "",
        "Skills with the same name in both trees — keep in sync or pick a primary owner:",
        "",
    ]
    # Canonical ownership decisions — when both agents have the same skill,
    # one version is the source of truth; the other mirrors it. Lets both
    # agents keep a working local copy without drift.
    canonical = {
        "obsidian": "openclaw",
        "llm-wiki": "hermes",
        "cross-machine-context-recovery": "hermes",
        "google-calendar-income-structure-audit": "openclaw",
        "messy-calendar-income-reconstruction": "openclaw",
    }
    for d in dupes:
        owner = canonical.get(d, "undecided")
        lines.append(f"- **{d}** — canonical owner: **{owner}** (other side mirrors)")
    if not dupes:
        lines.append("- _(none)_")
    lines += [
        "",
        f"## OpenClaw custom-skills ({len(oc)})",
        "",
        "_Location: `~/.openclaw/custom-skills/`_",
        "",
    ]
    for _, name, desc in oc:
        lines.append(f"- **{name}** — {desc}" if desc else f"- **{name}**")

    lines += [
        "",
        f"## Hermes skills ({len(hermes)})",
        "",
        "_Location: `~/.hermes/skills/<category>/<skill>/SKILL.md`_",
        "",
    ]
    for cat in sorted(by_cat):
        items = by_cat[cat]
        lines.append(f"### {cat} ({len(items)})")
        lines.append("")
        for name, desc in items:
            lines.append(f"- **{name}** — {desc[:140]}" if desc else f"- **{name}**")
        lines.append("")

    lines += [
        "## Regeneration",
        "",
        "Run manually:",
        "",
        "```bash",
        "/opt/homebrew/bin/python3 /Users/brian/dev/hermes-agent/agent_bus/scripts/build_skills_moc.py",
        "```",
        "",
        "Or use the `agent_bus` tool's `wiki_query` action to search the catalog content.",
        "",
    ]

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(lines)} lines, {len(hermes) + len(oc)} skills, {len(dupes)} dupes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
