/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
import { ClipboardCheck, History, ListChecks, ShieldAlert, SlidersHorizontal } from "lucide-react";
import { fetchJSON } from "@/lib/api";

type Row = Record<string, any>;
type Tab = "needs" | "proposals" | "evals" | "projects" | "live" | "history" | "governance";
const tabLabels: Record<Tab, string> = { needs: "Needs You", proposals: "Proposals", evals: "Evals", projects: "Projects", live: "Live Window", history: "History", governance: "Governance & Controls" };
const cls = (...parts: Array<string | false | null | undefined>) => parts.filter(Boolean).join(" ");
async function api<T>(url: string, init?: RequestInit) { return fetchJSON<T>(url, init); }

export default function ContextControlPage() {
  const [state, setState] = useState<Row | null>(null);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<Tab>("needs");
  const [drawer, setDrawer] = useState<Row | null>(null);
  const [rejecting, setRejecting] = useState<string | null>(null);
  const [reason, setReason] = useState("");
  const [approvedBlocks, setApprovedBlocks] = useState<Record<string, Record<string, boolean>>>({});

  const load = async () => { try { setErr(null); setState(await api<Row>("/api/context-control/state")); } catch (e: any) { setErr(e.message || String(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);

  const proposals = state?.proposals || [];
  const eval0Pass = state?.status?.eval_0 === "pass";
  const priority = useMemo(() => [...proposals].sort((a: Row, b: Row) => Number(!!b.safety_critical_blocks?.length) - Number(!!a.safety_critical_blocks?.length)), [proposals]);
  const approve = async (p: Row) => {
    const approvals = Object.entries(approvedBlocks[p.id] || {}).filter(([, v]) => v).map(([k]) => k);
    await api(`/api/context-control/proposals/${encodeURIComponent(p.id)}/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ safety_block_approvals: approvals }) });
    await load();
  };
  const reject = async (id: string) => {
    await api(`/api/context-control/proposals/${encodeURIComponent(id)}/reject`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) });
    setRejecting(null); setReason(""); await load();
  };
  const rollback = async () => { await api("/api/context-control/rollback", { method: "POST" }); await load(); };

  if (loading) return <div className="mf-page p-6">Loading Context control plane…</div>;
  if (err || !state) return <div className="mf-page p-6 text-red-700">Context Control API error: {err}</div>;

  return <div className="mf-page min-h-screen p-5 text-[var(--mf-text)]"><style>{tokens}</style><div className="mx-auto max-w-[1280px] space-y-4">
    <header className="mf-card p-5"><p className="mf-meta">CONTEXT CONTROL · RECOMMEND ONLY · NO LIVE CHANGES WITHOUT APPROVAL</p><div className="mt-2 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="font-serif text-2xl">Context control plane</h1><p className="mt-1 max-w-4xl text-sm text-[var(--mf-muted)]">The immutable baseline and one-click rollback win ties. This is a review and approval surface for agent context — never something that changes context on its own. Proposals are draft-only; nothing goes live without Jordan&apos;s approval.</p></div><Badge tone="green">Auto-apply disabled</Badge></div></header>
    <nav className="mf-strip sticky top-0 z-10 flex flex-wrap items-center gap-2 p-2 text-sm"><StatusJump label="Date" value={state.status.date} /><StatusJump label="Pending approvals" value={state.status.pending_approvals} /><StatusJump label="Eval 0" value={state.status.eval_0} /><StatusJump label="Override rate" value={state.status.override_rate} /><StatusJump label="Live overlay" value={state.status.live_overlay} /><StatusJump label="Rollback" value={state.status.rollback} /><StatusJump label="Managed scope" value={state.status.managed_scope} /><StatusJump label="Live window" value={state.status.live_window} /></nav>
    <div className="flex flex-wrap gap-2">{(Object.keys(tabLabels) as Tab[]).map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={cls("rounded-full border px-4 py-2 text-sm", activeTab === tab ? "border-[var(--mf-accent)] bg-white text-[var(--mf-accent)]" : "border-[var(--mf-border)] bg-[var(--mf-surface)] text-[var(--mf-muted)]")}>{tabLabels[tab]}</button>)}</div>

    {activeTab === "needs" && <NeedsYou state={state} priority={priority} setDrawer={setDrawer} approve={approve} reject={reject} rejecting={rejecting} setRejecting={setRejecting} reason={reason} setReason={setReason} approvedBlocks={approvedBlocks} setApprovedBlocks={setApprovedBlocks} eval0Pass={eval0Pass} />}
    {activeTab === "proposals" && <Panel title="Proposals" icon={<ListChecks />}>{priority.map((p: Row) => <ProposalCard key={p.id} proposal={p} setDrawer={setDrawer} approve={approve} reject={reject} rejecting={rejecting} setRejecting={setRejecting} reason={reason} setReason={setReason} approvedBlocks={approvedBlocks} setApprovedBlocks={setApprovedBlocks} eval0Pass={eval0Pass} />)}</Panel>}
    {activeTab === "evals" && <EvalsTab state={state} />}
    {activeTab === "projects" && <ProjectsTab state={state} />}
    {activeTab === "live" && <LiveTab state={state} />}
    {activeTab === "history" && <HistoryTab state={state} />}
    {activeTab === "governance" && <GovernanceTab state={state} rollback={rollback} />}
    {drawer && <DiffDrawer item={drawer} state={state} close={() => setDrawer(null)} />}
  </div></div>;
}

function NeedsYou({ state, priority, setDrawer, ...actions }: any) { const m = state.metrics; return <div className="space-y-4"><Panel title="Needs You" icon={<ClipboardCheck />}><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><Metric label="Pending approvals" value={m.pending_approvals.value} tone={tone(m.pending_approvals.tone)}/><Metric label="Safety (Eval 0)" value={m.safety.value} tone={tone(m.safety.tone)}/><Metric label="Override rate" value={m.override_rate.value} tone={tone(m.override_rate.tone)}/><Metric label="Tokens saved" value={m.tokens_saved.value} tone={tone(m.tokens_saved.tone)}/><Metric label="Stale findings" value={m.stale_findings.value} tone={tone(m.stale_findings.tone)}/><Metric label="Scope-leakage findings" value={m.scope_leakage_findings.value} tone={tone(m.scope_leakage_findings.tone)}/></div><div className="mt-4 space-y-3"><MorningBlock title="1. Awaiting your approval" empty="No approval decisions queued.">{priority.map((p: Row) => <ProposalCard key={p.id} proposal={p} setDrawer={setDrawer} compact {...actions} />)}</MorningBlock><MorningBlock title="2. Recommended fixes" rows={findingLines(state.recommended_fixes)} empty="No stale, duplicate, conflict, or scope-leakage findings."/><MorningBlock title="3. Live window" rows={[`Time left: ${state.status.live_window}`, `Override rate: ${state.status.override_rate}`, `Safety events: ${(state.override_log || []).filter((r: Row)=>r.safety_relevant).length}`]} empty="No live window active."/></div></Panel></div>; }
function ProposalCard({ proposal, setDrawer, approve, rejecting, setRejecting, reject, reason, setReason, approvedBlocks, setApprovedBlocks, eval0Pass, compact }: any) { const required = proposal.safety_critical_blocks || []; const allApproved = !required.length || required.every((b: string) => approvedBlocks[proposal.id]?.[b]); return <div className="mb-3 rounded-2xl border border-[var(--mf-border)] bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="font-semibold">{proposal.summary || proposal.id}</div><div className="mt-1 text-sm text-[var(--mf-muted)]">{proposal.project} · {proposal.safety_impact} · token delta {proposal.token_delta ?? "—"} · pass-rate {proposal.pass_rate_impact || "unknown"} · confidence {proposal.confidence ?? "—"}</div></div><Badge tone={required.length ? "red" : "amber"}>{proposal.status}</Badge></div>{required.length > 0 && <div className="mt-3 rounded-2xl border border-[var(--mf-border)] bg-[var(--mf-wash)] p-3 text-xs"><div className="mb-2 font-semibold">Safety-critical blocks require explicit per-block approval</div>{required.map((b: string) => <label key={b} className="mb-1 flex items-center gap-2"><input type="checkbox" checked={!!approvedBlocks[proposal.id]?.[b]} onChange={(e) => setApprovedBlocks((prev: Row) => ({ ...prev, [proposal.id]: { ...(prev[proposal.id] || {}), [b]: e.currentTarget.checked } }))}/>{b}</label>)}</div>}<div className="mt-3 flex flex-wrap gap-2"><button className="btn" disabled={!eval0Pass || !allApproved} onClick={() => approve(proposal)}>Approve</button><button className="btn-secondary" onClick={() => setRejecting(proposal.id)}>Reject</button><button className="btn-secondary" onClick={() => setDrawer(proposal)}>Open diff</button></div>{rejecting === proposal.id && <div className="mt-3 flex flex-col gap-2 rounded-2xl border border-[var(--mf-border)] bg-[var(--mf-wash)] p-3"><textarea className="field" value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Rejection reason — kept as training data, never deletes."/><button className="btn-secondary" disabled={!reason.trim()} onClick={() => reject(proposal.id)}>Record rejection</button></div>}{compact ? null : <div className="mt-2 text-xs text-[var(--mf-muted)]">Approve calls the gated switch only when Eval 0 is green. Reject records the reason and never deletes.</div>}</div>; }
function EvalsTab({ state }: any) { const e = state.evals || {}; const visible = e.visible_tasks || {}; return <div className="space-y-4"><Panel title="Eval 0 and task evals" icon={<ShieldAlert />}><div className="grid gap-3 md:grid-cols-4"><Metric label="Eval 0 safety" value={state.status.eval_0} tone={state.status.eval_0 === "pass" ? "green" : "red"}/><Metric label="Hidden aggregate" value={`${e.hidden_variants?.aggregate?.passed ?? 0}/${e.hidden_variants?.aggregate?.count ?? 0}`}/><Metric label="Task pass-rate" value={String(e.task_pass_rate ?? "—")}/><Metric label="Pass-rate/token" value={String(e.task_pass_rate_per_token ?? "—")}/></div><Table title="Visible tasks A–E" rows={Object.entries(visible).map(([k,v]: any)=>({ task:k, passed: String(!!v.passed) }))} cols={["task","passed"]}/><Table title="Candidate vs baseline" rows={[e.candidate_vs_baseline || {}]} cols={["token_delta","token_delta_pct"]}/><MorningBlock title="Verification budget" rows={[JSON.stringify(e.verification_budget || {})]} empty="No verification-budget report."/></Panel></div>; }
function ProjectsTab({ state }: any) { return <Panel title="Projects" icon={<SlidersHorizontal />}><div className="grid gap-3 lg:grid-cols-2">{state.projects.map((p: Row)=><div key={p.name} className="rounded-2xl border border-[var(--mf-border)] bg-white p-4"><div className="flex items-center justify-between"><div className="font-semibold">{p.name}</div><Badge tone={p.managed ? "green" : "slate"}>{p.managed ? "managed" : "unmanaged"}</Badge></div><div className="mt-2 grid gap-2 text-sm text-[var(--mf-muted)] sm:grid-cols-2"><div>Size: {p.current_size}</div><div>Last compiled: {p.last_compiled}</div><div>Pending: {p.pending_proposals}</div><div>Findings: {p.findings_count}</div><div>Eval 0: {p.eval_0}</div><div>Rollback: {p.rollback}</div></div></div>)}</div></Panel>; }
function LiveTab({ state }: any) { return <Panel title="Live Window" icon={<History />}><div className="grid gap-3 md:grid-cols-3"><Metric label="Time left" value={state.status.live_window}/><Metric label="Override rate" value={state.status.override_rate}/><Metric label="Safety events" value={(state.override_log || []).filter((r: Row)=>r.safety_relevant).length}/></div><Table title="Override/correction log" rows={state.override_log || []} cols={["event","at_utc","override","safety_relevant","description"]}/></Panel>; }
function HistoryTab({ state }: any) { return <Panel title="History" icon={<History />}><Table title="Switch history" rows={[state.history.latest_switch || {}]} cols={["switch_id","safety_verified","rollback_command"]}/><Table title="Rejections" rows={state.rejections || []} cols={["proposal_id","reason","training_data","deleted","at_utc"]}/></Panel>; }
function GovernanceTab({ state, rollback }: any) { return <Panel title="Governance & Controls" icon={<ShieldAlert />}><div className="rounded-2xl border border-[var(--mf-border)] bg-[var(--mf-wash)] p-3 text-sm">Page is read-only except gated approve, reject, and rollback. Auto-apply is disabled. Reject records training data and never deletes.</div><div className="mt-3 flex flex-wrap gap-2"><button className="btn" onClick={rollback}>Rollback now</button><Badge tone="green">Rollback always visible</Badge><Badge tone="amber">Approval required</Badge></div><pre className="mt-3 overflow-auto rounded-2xl bg-white p-3 text-xs">{JSON.stringify(state.governance, null, 2)}</pre></Panel>; }
function DiffDrawer({ item, state, close }: any) { const openFile = async (path: string) => { await api("/api/context-control/open-file", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ path }) }); }; const sourceFiles = ["reports/pilot-001/phase-c/diff-packet.json", "reports/pilot-001/phase-c/eval-report.json", "reports/pilot-001/phase-c/evidence-summary.md"]; return <div className="fixed inset-0 z-50 bg-black/30 p-4" onClick={close}><aside className="ml-auto h-full max-w-2xl overflow-auto rounded-3xl bg-[var(--mf-surface)] p-5 shadow-xl" onClick={(e)=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="font-serif text-xl">File / diff drill-down</h2><button className="btn-secondary" onClick={close}>Close</button></div><p className="mt-2 text-sm text-[var(--mf-muted)]">{item.summary || item.id}</p><Table title="Diff" rows={state.diff || []} cols={["block_id","reason","removed","added"]}/><div className="mt-3 rounded-2xl border border-[var(--mf-border)] bg-[var(--mf-wash)] p-3 text-sm">Full provenance: source file, content hash, last-verified date, affected agents/tools, token delta, rollback path. Open files uses the source paths exposed by the reports.</div><div className="mt-3 flex flex-wrap gap-2">{sourceFiles.map((path) => <button key={path} className="btn-secondary" onClick={() => openFile(path)}>Open file: {path.split("/").pop()}</button>)}</div><pre className="mt-3 overflow-auto rounded-2xl bg-white p-3 text-xs">{JSON.stringify({ item, rollback: state.governance?.rollback_command }, null, 2)}</pre></aside></div>; }
function MorningBlock({ title, rows, empty, children }: any) { return <div className="rounded-2xl border border-[var(--mf-border)] bg-white p-3"><div className="font-semibold">{title}</div>{children || (rows?.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--mf-muted)]">{rows.map((r: string, i: number)=><li key={i}>{r}</li>)}</ul> : <div className="mt-2 text-sm text-[var(--mf-muted)]">{empty}</div>)}</div>; }
function Panel({ title, icon, children }: any) { return <section className="mf-card p-5"><div className="mb-4 flex items-center gap-2 text-[var(--mf-text)]"><span className="text-[var(--mf-accent)]">{icon}</span><h2 className="font-serif text-xl">{title}</h2></div>{children}</section>; }
function Badge({ children, tone = "slate" }: any) { const colors: any = { green:"bg-[var(--mf-success)] text-white", amber:"bg-[var(--mf-warning)] text-white", red:"bg-[var(--mf-danger)] text-white", slate:"bg-[var(--mf-wash)] text-[var(--mf-muted)]" }; return <span className={cls("rounded-full px-2.5 py-1 text-xs", colors[tone])}>{children}</span>; }
function Metric({ label, value, tone = "blue" }: any) { const dot: any = { green:"var(--mf-success)", amber:"var(--mf-warning)", red:"var(--mf-danger)", blue:"var(--mf-info)" }; return <div className="rounded-2xl border border-[var(--mf-border)] bg-white p-3"><div className="mf-meta flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{background: dot[tone] || dot.blue}} />{label}</div><div className="mt-1 break-words font-mono text-lg text-[var(--mf-text)]">{value}</div></div>; }
function StatusJump({ label, value }: any) { return <span className="rounded-full border border-[var(--mf-border)] bg-white px-3 py-1"><span className="text-[var(--mf-muted)]">{label}: </span><b>{value}</b></span>; }
function Table({ title, rows, cols }: any) { return <div className="mt-3 overflow-auto rounded-2xl border border-[var(--mf-border)] bg-white p-3"><div className="mb-2 font-semibold">{title}</div><table className="w-full text-left text-xs"><thead><tr>{cols.map((c: string)=><th key={c} className="py-2 text-[var(--mf-muted)]">{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{(rows || []).map((r: Row, i: number)=><tr key={i} className="border-t border-[var(--mf-border)]">{cols.map((c: string)=><td key={c} className="max-w-64 break-words py-2 font-mono">{Array.isArray(r[c]) || typeof r[c] === "object" ? JSON.stringify(r[c] ?? "—") : String(r[c] ?? "—")}</td>)}</tr>)}</tbody></table></div>; }
function tone(value: string) { return value === "red" ? "red" : value === "amber" ? "amber" : "green"; }
function findingLines(findings: Row) { return Object.entries(findings || {}).flatMap(([k,v]: any) => Array.isArray(v) && v.length ? v.map((x: any) => `${k}: ${typeof x === "string" ? x : JSON.stringify(x)}`) : []); }
const tokens = `.mf-page { --mf-bg:#F0EEE6; --mf-surface:#FFFFFF; --mf-border:#E3E0D8; --mf-text:#1F1E1D; --mf-muted:#6B6A68; --mf-accent:#D97757; --mf-success:#5E7B5A; --mf-warning:#B8860B; --mf-danger:#C04A3E; --mf-info:#58738A; --mf-wash:#F8F6EF; background:var(--mf-bg); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,sans-serif; line-height:1.5; }
.mf-page * { box-sizing:border-box; text-transform:none; letter-spacing:normal; }
.mf-card { background:var(--mf-surface); border:1px solid var(--mf-border); border-radius:24px; box-shadow:0 10px 30px rgba(31,30,29,.04); }
.mf-strip { background:rgba(240,238,230,.94); border:1px solid var(--mf-border); border-radius:18px; backdrop-filter:blur(10px); }
.mf-meta { color:var(--mf-muted); font-size:11px; letter-spacing:.08em; text-transform:uppercase; }
.field { border:1px solid var(--mf-border); border-radius:12px; background:#fff; color:var(--mf-text); padding:8px 10px; font-size:14px; min-width:0; width:100%; max-width:100%; }
.btn { border-radius:12px; background:var(--mf-accent); color:white; padding:9px 14px; font-size:14px; font-weight:650; }
.btn:disabled { opacity:.45; cursor:not-allowed; }
.btn-secondary { border-radius:12px; border:1px solid var(--mf-border); background:white; color:var(--mf-text); padding:9px 14px; font-size:14px; font-weight:650; }`;
